### ISSUE TITLE
Control panel: cycling through advisories or cycles don't work after dragging a layer in the side panel

### ISSUE THREAD

**Issue by lstillwe** [RENCI/APSViz-UI-V3#150]
To reproduce ...
Start V3 UI
In the control panel cycle backward for either an advisory or model run cycle
Go to the the layers tray in the side panel
Drag the model run from the bottom to the top of the list.
Go back to control panel and try to cycle back again through the advisory or cycle
It will not cycle back anymore.

**Comment by PhillipsOwen** [comment]
after witnessing this it is only happening with 2 model runs in the tray. could this be a 0th index type of issue?

**Comment by PhillipsOwen** [comment]
the reason why this is not working is because although the filter is changing it is not triggering a new data gathering (setNewLayers()).

in this state hitting the "previous" button nothing happens.

however, if one were to hit the "next" button the filter change provokes a data gathering event. then the "previous" button starts working again.

**Comment by PhillipsOwen** [comment]
steps to reproduce:

- open the app.
- use the control panel to go back 2 cycles
- open the selected layers tray.
- drag the middle model run to the top

note how the control panel will not retrieve a previous cycle.

if you put these 2 console.log() entries in control-panel.js, line 275 you can see the issue pretty clearly.

console.log('\ntopLayers[0] filters:' + JSON.stringify(filters));
console.log('topLayers[0] newFilters:' + JSON.stringify(newFilters));

**Comment by lstillwe** [comment]
Fixed now.
