### ISSUE TITLE
forecast model output not showing up in situation where there are both non-DA and DA instances

### ISSUE THREAD

**Issue by BrianOBlanton** [RENCI/APSViz-UI-V3#235]
See slack messages in apsvizdebug for details:

https://renci.slack.com/archives/C05DZ3DHLNP/p1726278640749019

**Comment by BrianOBlanton** [comment]
I actually thought we resolved this issue earlier in the year, when Shintaro was testing out the DA system for the ncsc123 grid.  it is convenient to have both the DA and non-DA versions running so the impact of the assimilation (much lower error) can be directly seen in APSViz.

**Comment by jmpmcmanus** [comment]
The issue with instance names (DA, nonDA) runs has been resolved for a long time. Runs with different instance names do not conflict with each other. I will take a closer look at your slack message to understand what is going on there.

The problem with the Shintaro runs a few months back was different. His two runs had the same instance name and timemark, but the nowcast data had different values because he changed the run imputs. Adding the remove dup step to the ingest of nowcast and forecast data fixed this problem. If such a run occurs again the data for the earlier run will be removed. Your runs had the same instance name but different timemarks.

I reran the two coamps runs from PSC the had failed yesterday, and they got through. There have not been any new coamps.

Monday I'm going to take a closer look at why the PSC runs were taking so long.
________________________________
