### ISSUE TITLE
cycle arrows in legend don't work if a cycle is missing

### ISSUE THREAD

**Issue by rluettich** [RENCI/APSViz-UI-V3#254]
The < cycle # > feature in the legend is very nice for rapidly comparing a sequence of runs.  However, if a run is missing, e.g., for some reason the 06Z run isn't populated in apsviz, then the <  > keys don't work.  In this case it would be great if these keys could just skip over missing cycles so long as the model run data and cycle number are correct.

**Comment by PhillipsOwen** [comment]
can you please supply the model runs where this happens?

**Comment by PhillipsOwen** [comment]
can you please supply the model runs where this happens?

**Comment by PhillipsOwen** [comment]
please refer to issue #196 , line item number 1.

**Comment by PhillipsOwen** [comment]
i have not found an issue with the website on this. note that there are some model runs that didnt start at cycle 01.

for example, the "veerRight100" runs (Type: **veerRight100**, Grid: egom_v20b, Instance: egom_al09_nopp_sapelo) started at cycle 008. if for instance you loaded the most recent "veerRight100" (adv 014) you can only go back to adv 008 for that type of run.

there are other runs (Type: **ofcl**, Grid: egom_v20b, Instance: egom_al09_nopp_sapelo), that admittedly have a listing that looks very similar to "veerRight100", started at adv 001.

**Comment by PhillipsOwen** [comment]
this morning i discovered a UGA data anomaly that is related to this issue.

apparently somewhere along the line the suite process ID changed in the run properties between advisory 010 and 011. all other identifying run properties that we use for finding like model run groups remained the same.

when the suite uid changes a new instance id is issued. this is used to create the unique model run ID (ex: 4525-010-ofcl). in this case when the new suite UID came in it switched to an entirely different model run ID (4537-011-ofcl). 

since none of the other search criteria changed (run props: grid type, instance_name, event type, storm name, met class) we are seeing a discontinuity of the model runs in a group.

**Comment by BrianOBlanton** [comment]
does this referring to the issue in the orange ellipse?

![Screenshot 2024-10-08 at 10 14 19 AM](https://github.com/user-attachments/assets/5ed5b7b5-818c-429f-9e5d-0766cbbae88c)

**Comment by PhillipsOwen** [comment]
No. this is something else that Jim knows about.

closing this issue as this is a data anomaly when the instance ID ("process ID" run property) changes unexpectedly during a sequence of model runs.
