### ISSUE TITLE
Default layers - Force "official" hurricane runs

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/APSViz-UI-V3#288]
OP: Brian.

The ensemble simulations like "veer" are causing all sorts of problems since we don't have a hurricane track for the UI that reflects the modification to the storm.  Can we prevent the veer* layers from showing up as the default view?  Because of the order in which the ensembles are executed, they will almost always be the most recent for an NHC run.   

We still want them available thru the usual layer selection process, but just not as the default.

**Comment by PhillipsOwen** [comment]
I installed a hot fix to the UI data web service to force the default to be the latest "official hurricane" run.

this will have to be undone after the hurricane passes. A more permanent solution is needed here.

**Comment by PhillipsOwen** [comment]
Rick and I had a short slack discussion yesterday and he would like to make more changes to the default startup.

**Comment by PhillipsOwen** [comment]
"instance_name" questions...
- does it override on the nopp app data?
- does it override defaults already in place when a hurricane is active? 
- will an instance name ever be reused?

**Comment by BrianOBlanton** [comment]
- does it override on the nopp app data filter?

yes, there would need to be a separate endpoint for setting this, one for each production / aws site. 

- will there be a different instance name for the nopp app?

generally, yes, instance names are distinct 

- does it override defaults already in place ("ofcl" only) when a hurricane is active?

yes, it will

- will an instance name ever be reused?

Generally, we try not to do this, but it's not impossible for one to be reused.    Probably unlikely for tropicals, but more likely for synoptic / GFS

- will there be a character limit so it doesnt blowout places on the UI/V3 where shown.

they are generally short, <30 char, but we can impose such a constraint when the model operators set up an instance.

**Comment by PhillipsOwen** [comment]
i have a question related to the new default instance name implementation and the NOPP only default startup forcing ensemble name to be "coampsforecast". is this still needed?

**Comment by BrianOBlanton** [comment]
I think the default will always be coampsforecast for the NOPP side, since the coamps meteorology is part of the NOPP project.  But the ability to override the default may still be useful for the NOPP aite.

--

Cheers,

 [A black text on a white background  Description automatically generated]

Brian O. Blanton, Ph.D.
Director of Earth Data Sciences
Oceanographer
Renaissance Computing Institute
University of North Carolina at Chapel Hill
100 Europa Drive
Suite 540 Chapel Hill, NC, 27517

***@***.******@***.***>
919-445-9620 (O)



From: Phil Owen ***@***.***>
Date: Thursday, October 24, 2024 at 10:19 AM
To: RENCI/APSViz-UI-V3 ***@***.***>
Cc: Blanton, Brian ***@***.***>, Mention ***@***.***>
Subject: Re: [RENCI/APSViz-UI-V3] Default layers - Force "official" hurricane runs (Issue #288)

i have a question related to the new default instance name implementation and the NOPP only default startup forcing ensemble name to be "coampsforecast". is this still needed?

**Comment by lstillwe** [comment]
This is done
